services:
  node:
    image: node:20
    volumes:
      - ./app:/app
    working_dir: /app
    command: node server.js
    expose:
      - "4000"
    restart: unless-stopped
    networks:
      - app-network

  svelte:
    image: node:20
    volumes:
      - ./appV2:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    expose:
      - "5173"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev/conf.d:/etc/nginx/conf.d:ro
      - ./app/p/img:/usr/p/img
      - ./fallback:/usr/share/nginx/nginx
    depends_on:
      - node
      - svelte
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
