

services:
  node:
    image: node:20
    volumes:
      - ./app:/app
    working_dir: /app
    command: node server.js
    ports:
      - "4000:4000"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/webroot:/var/www/certbot
      - ./fallback:/usr/share/nginx/nginx
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    profiles: ["certbot"]
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c "sleep 5 &&
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${NODE_DOMAIN}"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"      # RTMP
      - "9000:9000/udp"  # SRT
    volumes:
      - ./nginx/mediamtx.yml:/etc/mediamtx.yml:ro
  


